### ISSUE TITLE
Ucc: FATAL ERROR: dosbox executable not found.

### ISSUE THREAD

**Issue by AryaisHere** [uditkarode/ucc#7]
**Describe the bug**
So i just installed ucc and when i run ucc command it says

FATAL ERROR: dosbox executable not found.

**Screenshots**
https://i.ibb.co/1nkPcZC/Screen-Shot-2020-10-21-at-12-23-58.png

**OS**
OS: Mac OSX 10.7.5
**Additional context**
How can i fix this? do i need to install dosbox?

**Comment by uditkarode** [comment]
Yes, you need to install DosBox. You can do that very easily with brew: `brew install dosbox`
