### ISSUE TITLE
If ucc path folder contains space so compiler not work

### ISSUE THREAD

**Issue by Aditya7851-AdiStarCoders** [uditkarode/ucc#9]
**Describe the bug**
If ucc path folder contains space so compiler not work
e.g   c://program files/ucc --> not  work because having space in "program files" folder

e.g   c://programfiles/ucc -->work because not any space in programfiles folder

**To Reproduce**
1. just paste ucc into space contains folder
2. then excute compiler with any c/cpp file for compiler
3. See error

**Desktop (please complete the following information):**
 - OS: windows
 - DosBox Version [e.g. 0.74-2]  :  0.74-2
 - UCC Version [e.g. 1]   current 23days ago commited

**Comment by uditkarode** [comment]
Fixed in b090dcdc951a1d56f968e8a6f528875cffaaef4a
